# Generated by Django 4.2.4 on 2023-09-02 08:00

import apps.carpool.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Simple name of the car make.', max_length=50, verbose_name='car make name')),
                ('official_name', models.CharField(help_text='Official name of the car make (including Ltd. or GmbH).', max_length=1000, verbose_name='car make official name')),
            ],
            options={
                'verbose_name': 'car make',
                'verbose_name_plural': 'car makes',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Model of a car.', max_length=50, verbose_name='car model')),
                ('make', models.ForeignKey(help_text='Make of the car model.', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='carpool.carmake', verbose_name='car make')),
            ],
            options={
                'verbose_name': 'car model',
                'verbose_name_plural': 'car models',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('car_id', models.CharField(help_text='Internal car ID that consists of a string with C-prefix and up to 10 decimal digits.', max_length=50, unique=True, validators=[apps.carpool.validators.validate_car_id], verbose_name='internal car ID')),
                ('registration_number', models.CharField(help_text='Car registration number that consists from 8 characters with at least one digit.', max_length=8, verbose_name='car registration number')),
                ('model', models.ForeignKey(help_text='Model of the given car.', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carpool.carmodel', verbose_name='car')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
            },
        ),
    ]
