# Generated by Django 4.2.4 on 2023-09-02 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('to_rent_at', models.DateTimeField(help_text='Timestamp representing the time intent when a car shall be acquired from the rental.', verbose_name='to rent at')),
                ('to_return_at', models.DateTimeField(help_text='Timestamp representing time intent when a car shall be returned to the rental.', verbose_name='to return at')),
                ('request_id', models.UUIDField(help_text='ID of request that is internally generated as soon as reservation request is pending.', null=True, verbose_name='request ID')),
                ('client_name', models.CharField(help_text='Name of the client who reserved the car rental.', max_length=100, verbose_name='client name')),
                ('car', models.ForeignKey(help_text='The car that has been pre-selected for the rental', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='carpool.car', verbose_name='car for rent')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
            },
        ),
    ]
